slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: os_lidar
    scan_topic: /ouster/scan_multi
    use_scan_matching: true
    use_scan_matching_only: false

    resolution: 0.05
    maximum_laser_range: 60.0
    minimum_time_interval: 0.05

    scan_buffer_size: 80
    scan_buffer_max_size: 1000
    loop_closure_enable: true
    loop_closure_threshold: 0.15

    transform_timeout: 0.07
    tf_publish_period: 0.05
