a200_0000:
  teleop_twist_joy_node:
    ros__parameters:
      publish_stamped_twist: True
      use_sim_time: False
      axis_linear.x: 1
      scale_linear.x: 0.4
      scale_linear_turbo.x: 1.0
      axis_angular.yaw: 0
      scale_angular.yaw: 0.6
      scale_angular_turbo.yaw: 1.2
      enable_button: 4
      enable_turbo_button: 5
  joy_node:
    ros__parameters:
      use_sim_time: False
      deadzone: 0.1
      autorepeat_rate: 20.0
      dev: '/dev/input/js0'
  bt_cutoff_node:
    ros__parameters:
      quality_cutoff: 20
